import { EntryQueue } from "@/components/entry-queue";
import { availableCrmNames } from "@/lib/available-crm-names";
import { createClient } from "@/lib/supabase/server";

export default async function QueuePage({ searchParams }: { searchParams: Promise<{ branch?: string; completed?: string }> }) {
  const params = await searchParams; const supabase = await createClient(); const [{ data: profileRows }, { data: auth }] = await Promise.all([supabase.rpc("get_my_profile"), supabase.auth.getUser()]); const profile = profileRows?.[0]; if (!profile || !auth.user) return null;
  const [{ data: user }, { data: branches }] = await Promise.all([supabase.from("users").select("branch_id").eq("id", auth.user.id).single(), supabase.from("branches").select("id,name").eq("active", true).order("name")]); const activeBranches = branches ?? [];
  const selectedBranchId = profile.role === "super_admin" && activeBranches.some((branch) => branch.id === params.branch) ? params.branch! : user?.branch_id ?? activeBranches[0]?.id ?? ""; const today = new Date().toISOString().slice(0, 10);
  const [{ data: allocation }, { data: availability }, { data: queue }] = selectedBranchId ? await Promise.all([supabase.from("crm_allocation").select("crm_name").eq("branch_id", selectedBranchId).eq("active", true).order("crm_name"), supabase.from("crm_daily_availability").select("crm_name,is_available").eq("branch_id", selectedBranchId).eq("date", today), supabase.from("entry_queue").select("id,token,client_name,mobile,assigned_crm_name,status,created_at,client_id").eq("branch_id", selectedBranchId).gte("created_at", today).order("created_at", { ascending: false })]) : [{ data: [] }, { data: [] }, { data: [] }];
  return <main className="mx-auto max-w-7xl px-5 py-7"><div><p className="text-sm font-semibold uppercase tracking-wider text-amber-800">Front desk</p><h1 className="mt-1 text-3xl font-semibold">Client walk-in form</h1></div><EntryQueue key={selectedBranchId} profile={{ role: profile.role, branchId: user?.branch_id ?? null }} selectedBranchId={selectedBranchId} branches={activeBranches} crms={availableCrmNames(allocation ?? [], availability ?? [])} initialItems={queue ?? []} completedName={params.completed} /></main>;
}
