import { FollowupQueue } from "@/components/followup-queue";
import { createClient } from "@/lib/supabase/server";
export default async function FollowupsPage() {
 const supabase=await createClient(); const [{data:profileRows},{data:auth}] = await Promise.all([supabase.rpc("get_my_profile"),supabase.auth.getUser()]); const profile=profileRows?.[0]; if(!profile||!auth.user)return null;
 const db=supabase as any; const {data:followups}=await db.from("not_bought_followups").select("id,client_id,reference_number,status,next_followup_date,remark,branch_id,source_timeline_id,source_visit_form_id,clients!inner(primary_name,primary_phone),client_timeline(event_date,crm_name,seen_categories,product_requirement),visit_forms(not_bought_reasons,not_bought_other)");
 const rows=followups??[]; const ids=rows.map((row:any)=>row.id); const {data:history}=ids.length?await db.from("not_bought_history").select("followup_id,remark,created_at").in("followup_id",ids).order("created_at",{ascending:false}):{data:[]}; const byId=new Map<string,any[]>(); for(const entry of history??[])byId.set(entry.followup_id,[...(byId.get(entry.followup_id)??[]),entry]);
 const items=rows.map((row:any)=>{const timeline=row.client_timeline??{};const form=row.visit_forms??{};const h=byId.get(row.id)??[];return {id:row.id,client_id:row.client_id,reference_number:row.reference_number,status:row.status,next_followup_date:row.next_followup_date,remark:row.remark,branch_id:row.branch_id,client_name:row.clients.primary_name,phone:row.clients.primary_phone,crm_name:timeline.crm_name??"",visit_date:timeline.event_date??null,reason:[...(form.not_bought_reasons??[]),form.not_bought_other].filter(Boolean).join(", "),seen_categories:(timeline.seen_categories??[]).join(", "),product_requirement:timeline.product_requirement??"",followup_count:h.length,history_count:h.length,remark_history:h.map((entry:any)=>entry.remark).filter(Boolean).join("\n")};});
 const crmNames=[...new Set(items.map((item:any)=>item.crm_name).filter(Boolean))].sort() as string[]; return <FollowupQueue role={profile.role} branchId={null} items={items} crmNames={crmNames}/>;
}
