"use client";
import Link from "next/link";
import { type FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { phoneDigits } from "@/lib/clients";
import { createClient } from "@/lib/supabase/client";
type Item = { id: string; token: string; client_name: string; mobile: string; assigned_crm_name: string | null; status: string; created_at: string; client_id: string | null };
export function EntryQueue({ profile, selectedBranchId, branches, crms, initialItems }: { profile: { role: string; branchId: string | null }; selectedBranchId: string; branches: { id: string; name: string }[]; crms: string[]; initialItems: Item[] }) {
  const router = useRouter(); const [name, setName] = useState(""); const [mobile, setMobile] = useState(""); const [crm, setCrm] = useState(""); const [branch, setBranch] = useState(selectedBranchId); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); if (!name.trim() || phoneDigits(mobile).length !== 10 || !branch) { setMessage("Name, 10-digit mobile, and branch are required."); return; } setSaving(true); const { data, error } = await createClient().rpc("create_entry_queue", { p_client_name: name, p_mobile: mobile, p_branch_id: branch, p_assigned_crm_name: crm || undefined }); setSaving(false); if (error || !data?.[0]) { setMessage("Could not create the queue entry. Check the branch and CRM availability."); return; } setMessage(`Token ${data[0].token} created (${data[0].client_type} client).`); setName(""); setMobile(""); setCrm(""); router.refresh(); }
  return <div className="mt-6 grid gap-6 lg:grid-cols-[380px_1fr]"><form onSubmit={submit} className="space-y-4 rounded-xl border bg-white p-5"><h2 className="font-semibold">New token</h2><label className="block text-sm">Client name<input className="mt-1 w-full rounded border p-2" value={name} onChange={(event) => setName(event.target.value)} /></label><label className="block text-sm">Mobile<input className="mt-1 w-full rounded border p-2" inputMode="numeric" value={mobile} onChange={(event) => setMobile(event.target.value)} /></label>{profile.role === "super_admin" ? <label className="block text-sm">Branch<select className="mt-1 w-full rounded border p-2" value={branch} onChange={(event) => { setBranch(event.target.value); setCrm(""); router.push(`/queue?branch=${event.target.value}`); }}><option value="">Choose branch</option>{branches.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label> : null}<label className="block text-sm">Assigned CRM / salesperson<select className="mt-1 w-full rounded border p-2" value={crm} onChange={(event) => setCrm(event.target.value)}><option value="">Unassigned</option>{crms.map((item) => <option value={item} key={item}>{item}</option>)}</select></label><button disabled={saving} className="rounded bg-amber-800 px-4 py-2 font-medium text-white disabled:opacity-50">{saving ? "Creating…" : "Create token"}</button>{message ? <p className="text-sm text-stone-700">{message}</p> : null}</form><section className="overflow-hidden rounded-xl border bg-white"><div className="border-b p-4"><h2 className="font-semibold">CRM Present Today</h2><p className="mt-1 text-sm text-stone-600">{crms.length ? crms.join(", ") : "No active CRM is available for this branch today."}</p></div><div className="border-b p-4"><h2 className="font-semibold">Today’s entries</h2></div>{initialItems.length ? initialItems.map((item) => <article key={item.id} className="grid gap-2 border-b p-4 text-sm md:grid-cols-[110px_1fr_1fr_100px_120px]"><b>{item.token}</b><span>{item.client_name}<br /><span className="text-stone-500">{item.mobile}</span></span><span>{item.assigned_crm_name ?? "Unassigned"}</span><span className="capitalize">{item.status}</span><Link className="font-medium text-amber-800 underline" href={`/visits/new?queue=${item.id}`}>{item.status === "complete" ? "View visit" : "Open form"}</Link></article>) : <p className="p-5 text-sm text-stone-600">No entries yet today.</p>}</section></div>;
}
