/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";

import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";

import { ClientSearch } from "@/components/client-search";
import { phoneDigits } from "@/lib/clients";
import { createClient } from "@/lib/supabase/client";

type SelectedClient = { client_id: string; primary_name: string; primary_phone: string };
export function ReferralEntry({ role, branchId, branches }: { role: string; branchId: string | null; branches: { id: string; name: string }[] }) {
  const router = useRouter(); const [client, setClient] = useState<SelectedClient | null>(null); const [name, setName] = useState(""); const [phone, setPhone] = useState(""); const [crmName, setCrmName] = useState(""); const [branch, setBranch] = useState(branchId ?? ""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); if (!client || !name.trim() || phoneDigits(phone).length !== 10 || (role === "super_admin" && !branch)) { setMessage("Choose a referring client, enter a name and 10-digit number, and choose a branch when required."); return; } setSaving(true); setMessage(""); const { error } = await (createClient() as any).rpc("create_manual_referral", { p_client_id: client.client_id, p_referral_name: name, p_referral_number: phoneDigits(phone), p_crm_name: crmName || undefined, p_branch_id: role === "super_admin" ? branch : undefined }); setSaving(false); if (error) { setMessage(error.message.includes("own branch") ? "Only your own branch or a super admin can log this referral." : "Could not log the referral. Check the details and try again."); return; } router.push("/referrals"); router.refresh(); }
  return <section className="rounded-xl border bg-white p-5"><h2 className="text-lg font-semibold">Log a referral</h2><p className="mt-1 text-sm text-stone-600">For referrals received outside a walk-in visit.</p><form className="mt-4 grid gap-4 md:grid-cols-2" onSubmit={submit}><div className="md:col-span-2"><label className="text-sm font-medium">Referring client *</label>{client ? <div className="mt-1 flex items-center justify-between rounded border bg-stone-50 p-3 text-sm"><span><b>{client.primary_name}</b> · {client.primary_phone}</span><button type="button" className="underline" onClick={() => setClient(null)}>Change</button></div> : <div className="mt-1"><ClientSearch onSelect={(result) => setClient(result)} /></div>}</div><label className="text-sm font-medium">Referral name *<input className="mt-1 block w-full rounded border p-2" maxLength={160} value={name} onChange={(event) => setName(event.target.value)} /></label><label className="text-sm font-medium">Referral number *<input className="mt-1 block w-full rounded border p-2" inputMode="numeric" value={phone} onChange={(event) => setPhone(event.target.value)} placeholder="98765 43210" /></label><label className="text-sm font-medium">Salesperson / CRM name<input className="mt-1 block w-full rounded border p-2" maxLength={160} value={crmName} onChange={(event) => setCrmName(event.target.value)} /></label>{role === "super_admin" ? <label className="text-sm font-medium">Origin branch *<select className="mt-1 block w-full rounded border p-2" value={branch} onChange={(event) => setBranch(event.target.value)}><option value="">Choose branch</option>{branches.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label> : null}<div className="md:col-span-2"><button className="rounded bg-amber-800 px-4 py-2 text-sm font-medium text-white disabled:opacity-50" disabled={saving}>{saving ? "Saving…" : "Log referral"}</button>{message ? <p role="alert" className="mt-2 text-sm text-red-700">{message}</p> : null}</div></form></section>;
}
