-- Phase 1: session-bound client search, atomic create, and audit hygiene.
CREATE OR REPLACE FUNCTION "public"."set_client_profile_editor"() RETURNS trigger LANGUAGE plpgsql SECURITY INVOKER SET search_path = '' AS $$ BEGIN NEW.profile_updated_at := CURRENT_TIMESTAMP; NEW.profile_updated_by := "auth"."uid"(); RETURN NEW; END; $$;
CREATE TRIGGER "clients_set_profile_editor" BEFORE UPDATE ON "public"."clients" FOR EACH ROW EXECUTE FUNCTION "public"."set_client_profile_editor"();
CREATE OR REPLACE FUNCTION "public"."sync_client_phone_index"() RETURNS trigger LANGUAGE plpgsql SECURITY INVOKER SET search_path = '' AS $$ DECLARE phone_value text; BEGIN DELETE FROM "public"."client_phone_index" WHERE client_id = NEW.client_id; FOREACH phone_value IN ARRAY array_cat(ARRAY[NEW.primary_phone, NEW.secondary_phone, NEW.billing_phone], COALESCE(NEW.other_known_phones, ARRAY[]::text[])) LOOP IF phone_value IS NOT NULL AND length(regexp_replace(phone_value, '[^0-9]', '', 'g')) >= 10 THEN INSERT INTO "public"."client_phone_index" (phone, client_id) VALUES (phone_value, NEW.client_id); END IF; END LOOP; RETURN NEW; END; $$;
CREATE TRIGGER "clients_sync_phone_index" AFTER INSERT OR UPDATE OF primary_phone, secondary_phone, billing_phone, other_known_phones ON "public"."clients" FOR EACH ROW EXECUTE FUNCTION "public"."sync_client_phone_index"();
CREATE OR REPLACE FUNCTION "public"."audit_client_changes"() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$ DECLARE changed_field text; actor_id uuid; audit_source text; BEGIN actor_id := COALESCE("auth"."uid"(), NEW.profile_updated_by); audit_source := COALESCE(NULLIF(current_setting('app.audit_source', true), ''), 'database_trigger'); FOR changed_field IN SELECT new_fields.key FROM jsonb_each(to_jsonb(NEW)) AS new_fields WHERE new_fields.key NOT IN ('profile_updated_at', 'profile_updated_by') AND (to_jsonb(OLD) -> new_fields.key) IS DISTINCT FROM (to_jsonb(NEW) -> new_fields.key) LOOP INSERT INTO "public"."client_edit_log" (client_id, edited_by, source, field_name, old_value, new_value) VALUES (NEW.client_id, actor_id, audit_source, changed_field, to_jsonb(OLD) -> changed_field, to_jsonb(NEW) -> changed_field); END LOOP; RETURN NEW; END; $$;
CREATE OR REPLACE FUNCTION "public"."search_clients"(search_text text, result_limit integer DEFAULT 8) RETURNS TABLE(client_id uuid, primary_name text, primary_phone text, last_visit_date timestamptz, last_branch_name text, matched_phone text) LANGUAGE sql STABLE SECURITY INVOKER SET search_path = '' AS $$ WITH input AS (SELECT trim(search_text) AS value, regexp_replace(search_text, '[^0-9]', '', 'g') AS digits) SELECT c.client_id, c.primary_name::text, c.primary_phone::text, c.last_visit_date, b.name::text, p.phone::text FROM "public"."clients" c LEFT JOIN "public"."branches" b ON b.id = c.last_branch_id LEFT JOIN LATERAL (SELECT pi.phone FROM "public"."client_phone_index" pi, input WHERE pi.client_id = c.client_id AND input.digits <> '' AND pi.phone LIKE '%' || right(input.digits, 10) || '%' ORDER BY (pi.phone = right(input.digits, 10)) DESC LIMIT 1) p ON true, input WHERE "public"."current_user_role"() IS NOT NULL AND ((length(input.digits) >= 3 AND p.phone IS NOT NULL) OR (length(input.value) >= 3 AND (c.primary_name ILIKE '%' || input.value || '%' OR EXISTS (SELECT 1 FROM unnest(c.other_names) name WHERE name ILIKE '%' || input.value || '%')))) ORDER BY (p.phone = right(input.digits, 10)) DESC NULLS LAST, c.last_visit_date DESC NULLS LAST, c.primary_name LIMIT LEAST(GREATEST(result_limit, 1), 20); $$;
CREATE OR REPLACE FUNCTION "public"."create_client_with_phone"(p_primary_name text, p_primary_phone text, p_gender text DEFAULT NULL, p_branch_id uuid DEFAULT NULL) RETURNS uuid LANGUAGE plpgsql SECURITY INVOKER SET search_path = '' AS $$ DECLARE actor_role "public"."user_role"; own_branch uuid; target_branch uuid; new_client_id uuid; phone_digits text; BEGIN actor_role := "public"."current_user_role"(); own_branch := "public"."current_user_branch_id"(); IF actor_role IS NULL THEN RAISE EXCEPTION 'active CRM profile required' USING ERRCODE = 'insufficient_privilege'; END IF; IF length(trim(COALESCE(p_primary_name, ''))) = 0 THEN RAISE EXCEPTION 'primary name is required' USING ERRCODE = 'check_violation'; END IF; phone_digits := right(regexp_replace(COALESCE(p_primary_phone, ''), '[^0-9]', '', 'g'), 10); IF length(phone_digits) <> 10 THEN RAISE EXCEPTION 'phone must contain at least 10 digits' USING ERRCODE = 'check_violation'; END IF; IF actor_role = 'super_admin' THEN target_branch := p_branch_id; ELSE target_branch := own_branch; END IF; IF target_branch IS NULL OR NOT EXISTS (SELECT 1 FROM "public"."branches" WHERE id = target_branch AND active = true) THEN RAISE EXCEPTION 'an active branch is required' USING ERRCODE = 'check_violation'; END IF; INSERT INTO "public"."clients" (primary_name, primary_phone, gender, last_branch_id) VALUES (trim(p_primary_name), phone_digits, NULLIF(trim(p_gender), ''), target_branch) RETURNING client_id INTO new_client_id; RETURN new_client_id; END; $$;
REVOKE ALL ON FUNCTION "public"."search_clients"(text, integer) FROM PUBLIC; REVOKE ALL ON FUNCTION "public"."create_client_with_phone"(text, text, text, uuid) FROM PUBLIC; GRANT EXECUTE ON FUNCTION "public"."search_clients"(text, integer) TO authenticated; GRANT EXECUTE ON FUNCTION "public"."create_client_with_phone"(text, text, text, uuid) TO authenticated;
GRANT USAGE ON SCHEMA "auth" TO authenticated;
CREATE POLICY "active_staff_read_branches" ON "public"."branches" FOR SELECT TO authenticated USING ("public"."current_user_role"() IS NOT NULL);
CREATE POLICY "active_staff_read_users" ON "public"."users" FOR SELECT TO authenticated USING ("public"."current_user_role"() IS NOT NULL);
