import Link from "next/link";
import { DashboardFilter } from "@/components/dashboard-filter";
import { TrendChart } from "@/components/trend-chart";
import { StatusDistributionChart } from "@/components/status-distribution-chart";
import { buildDashboardData, dashboardRange, endExclusive, startInclusive } from "@/lib/dashboard";
import { displayDate } from "@/lib/clients";
import { createClient } from "@/lib/supabase/server";

const statLabels = [["walkIns", "Total walk-ins"], ["notBought", "Not bought"], ["bought", "Bought (ready product)"], ["orderPlaced", "Order placed"], ["repairPlaced", "Repair placed"], ["orderPickup", "Order pickup"], ["repairPickup", "Repair pickup"], ["upsale", "Upsale"], ["productReturn", "Product return"]] as const;

export default async function DashboardPage({ searchParams }: { searchParams: Promise<{ preset?: string; start?: string; end?: string }> }) {
  const range = dashboardRange(await searchParams); const supabase = await createClient(); const from = startInclusive(range); const until = endExclusive(range);
  // No branch predicate: dashboard viewing is intentionally global for every active role.
  const [visitsResponse, followupsResponse, referralsResponse] = await Promise.all([
    supabase.from("client_timeline").select("id,event_date,event_type,buy_status,branch_id,crm_name,remark,reference_number,client_id,branch:branches(name),client:clients(primary_name),salesperson:users(name)").gte("event_date", from).lt("event_date", until),
    supabase.from("not_bought_followups").select("status,next_followup_date,created_at").gte("created_at", from).lt("created_at", until),
    supabase.from("referral_calling").select("status,next_followup_date,created_at").gte("created_at", from).lt("created_at", until),
  ]);
  const data = buildDashboardData(visitsResponse.data ?? [], followupsResponse.data ?? [], referralsResponse.data ?? [], new Date().toISOString().slice(0, 10));
  return <main className="mx-auto max-w-7xl px-5 py-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-wider text-amber-800">Global performance</p><h1 className="mt-1 text-3xl font-semibold">Dashboard</h1><p className="mt-2 text-stone-600">{displayDate(range.start)} to {displayDate(range.end)} · same view for every active CRM role.</p></div><DashboardFilter start={range.start} end={range.end} preset={range.preset} /></div>
    <section className="mt-6"><h2 className="text-lg font-semibold">Visit and sales activity</h2><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5">{statLabels.map(([key, label]) => <article className="rounded-xl border bg-white p-4" key={key}><p className="text-xs font-medium uppercase tracking-wide text-stone-500">{label}</p><p className="mt-2 text-3xl font-semibold">{data.totals[key]}</p></article>)}</div></section>
    <section className="mt-7"><h2 className="text-lg font-semibold">Operational queues</h2><div className="mt-3 grid gap-3 md:grid-cols-2"><article className="rounded-xl border bg-white p-5"><p className="font-medium">Not-bought follow-ups</p><p className="mt-3 text-3xl font-semibold">{data.operations.pendingFollowups} <span className="text-sm font-normal text-stone-600">pending</span></p><p className="mt-1 text-sm text-red-700">{data.operations.overdueFollowups} overdue</p><Link href="/followups" className="mt-3 inline-block text-sm font-medium text-amber-800 underline">Open follow-up queue</Link></article><article className="rounded-xl border bg-white p-5"><p className="font-medium">Referral calling</p><p className="mt-3 text-3xl font-semibold">{data.operations.pendingReferrals} <span className="text-sm font-normal text-stone-600">pending</span></p><p className="mt-1 text-sm text-red-700">{data.operations.overdueReferrals} overdue</p><Link href="/referrals" className="mt-3 inline-block text-sm font-medium text-amber-800 underline">Open referral queue</Link></article></div></section>
    <section className="mt-7 grid gap-6 lg:grid-cols-2"><section className="overflow-hidden rounded-xl border bg-white"><div className="border-b p-4"><h2 className="text-lg font-semibold">Visits trend</h2><p className="text-sm text-stone-600">Daily total, ready-product bought, and not-bought visits.</p></div><TrendChart points={data.trend} /></section><section className="overflow-hidden rounded-xl border bg-white"><div className="border-b p-4"><h2 className="text-lg font-semibold">Walk-in status distribution</h2><p className="text-sm text-stone-600">Status breakdown for the selected range.</p></div><StatusDistributionChart total={data.totals.walkIns} items={data.statusDistribution} /></section></section>
    <section className="mt-7 grid gap-6 lg:grid-cols-2"><Breakdown title="Branch comparison" rows={data.branchBreakdown} /><Breakdown title="CRM / salesperson comparison" rows={data.crmBreakdown} /></section>
    <section className="mt-7 overflow-hidden rounded-xl border bg-white"><div className="border-b p-4"><h2 className="text-lg font-semibold">Recent visits</h2><p className="text-sm text-stone-600">Latest 25 visits in the selected range.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-stone-50 text-xs uppercase text-stone-600"><tr><th className="p-3">Client</th><th className="p-3">Event</th><th className="p-3">Buy status</th><th className="p-3">Branch</th><th className="p-3">Salesperson</th><th className="p-3">Remark</th><th className="p-3">Reference</th></tr></thead><tbody>{data.recentVisits.length ? data.recentVisits.map((visit) => <tr className="border-t" key={visit.id}><td className="p-3"><Link className="font-medium text-amber-800 underline" href={`/clients/${visit.client_id}`}>{visit.client?.primary_name ?? "Client record"}</Link></td><td className="p-3">{visit.event_type.replaceAll("_", " ")}</td><td className="p-3">{visit.buy_status?.replaceAll("_", " ") ?? "—"}</td><td className="p-3">{visit.branch?.name ?? "—"}</td><td className="p-3">{visit.crm_name ?? visit.salesperson?.name ?? "—"}</td><td className="max-w-64 truncate p-3" title={visit.remark ?? undefined}>{visit.remark ?? "—"}</td><td className="p-3">{visit.reference_number ?? "—"}</td></tr>) : <tr><td className="p-5 text-stone-600" colSpan={7}>No visits in this date range.</td></tr>}</tbody></table></div></section>
  </main>;
}

function Breakdown({ title, rows }: { title: string; rows: { name: string; visits: number; bought: number; buyRate: number }[] }) {
  return <section className="overflow-hidden rounded-xl border bg-white"><div className="border-b p-4"><h2 className="text-lg font-semibold">{title}</h2><p className="text-sm text-stone-600">Sorted by visits; buy rate uses ready-product bought ÷ total visits.</p></div><table className="w-full text-left text-sm"><thead className="bg-stone-50 text-xs uppercase text-stone-600"><tr><th className="p-3">Name</th><th className="p-3">Visits</th><th className="p-3">Bought</th><th className="p-3">Buy rate</th></tr></thead><tbody>{rows.length ? rows.map((row) => <tr className="border-t" key={row.name}><td className="p-3 font-medium">{row.name}</td><td className="p-3">{row.visits}</td><td className="p-3">{row.bought}</td><td className="p-3">{(row.buyRate * 100).toFixed(1)}%</td></tr>) : <tr><td colSpan={4} className="p-5 text-stone-600">No visits in this date range.</td></tr>}</tbody></table></section>;
}
